# Generated by Django 5.0.3 on 2024-04-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_book_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
